import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// @ts-ignore
import type { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const standardLinks: SidebarConfig = [
    {
        type: 'link',
        label: 'ShiftControl website',
        href: 'https://shiftcontrol.io',
    },
    {
        type: 'link',
        label: 'Release Notes',
        href: 'https://journey.shiftcontrol.io',
    },
    {
        type: 'link',
        label: 'Log in to ShiftControl',
        href: 'https://app.shiftcontrol.io',

    },
    {
        type: 'link',
        label: 'Support',
        href: 'mailto:support@shiftcontrol.io',
    },
];

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    mainSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'Get Started',
            items: [
                'introduction',
                'getting-started/quickstart',
            ],
        },
        {
            type: 'category',
            collapsed: false,
            label: 'Using ShiftControl (Admins)',
            items: [
                {
                    type: 'category',
                    label: 'Dashboards',
                    link: {
                        type: 'generated-index',
                        title: 'Dashboards',
                        description: 'Monitor OAuth permissions, track SaaS spending, and spot security risks across your organization.',
                        slug: '/using-shiftcontrol/Dashboards',
                        keywords: ['dashboards'],
                    },
                    items: [
                        'using-shiftcontrol/Dashboards/app-permissions',
                        'using-shiftcontrol/Dashboards/app-spend',
                    ],
                },
                'using-shiftcontrol/using-the-command-bar',
                'using-shiftcontrol/task-management',
                {
                    type: 'category',
                    label: 'Users',
                    link: {
                        type: 'generated-index',
                        title: 'Users',
                        description: 'Add, edit, and manage every person in your organization. Control access, onboard new hires, and offboard departing employees.',
                        slug: '/using-shiftcontrol/Users',
                        keywords: ['users','user-management'],
                    },
                    items: [
                        'using-shiftcontrol/Users/User-management',
                        'using-shiftcontrol/Users/Viewing-a-user',
                        'using-shiftcontrol/Users/Adding-a-user',
                        'using-shiftcontrol/Users/Editing-a-user',
                    ],
                },
                {
                    type: 'category',
                    label: 'Groups',
                    link: {
                        type: 'generated-index',
                        title: 'Groups',
                        description: 'Organize users into groups that automatically control app access, email distribution, and security policies.',
                        slug: '/using-shiftcontrol/Groups',
                        keywords: ['groups','group-management'],
                    },
                    items: [
                        'using-shiftcontrol/Groups/Group-management',
                        'using-shiftcontrol/Groups/Viewing-a-group',
                        'using-shiftcontrol/Groups/Adding-a-group',
                        'using-shiftcontrol/Groups/Editing-a-group',
                    ],
                },
                {
                    type: 'category',
                    label: 'Apps',
                    link: {
                        type: 'generated-index',
                        title: 'Apps',
                        description: 'Manage your SaaS applications, discover shadow IT, control SSO, and track software costs across your org.',
                        slug: '/using-shiftcontrol/Apps',
                        keywords: ['apps','app-management'],
                    },
                    items: [
                        'using-shiftcontrol/Apps/App-management',
                        'using-shiftcontrol/Apps/Viewing-an-app',
                        'using-shiftcontrol/Apps/Adding-an-app',
                        'using-shiftcontrol/Apps/Editing-an-app',
                        'using-shiftcontrol/Apps/App-discovery',
                    ],
                },
                {
                    type: 'category',
                    label: 'Reports',
                    link: {
                        type: 'generated-index',
                        title: 'Reports',
                        description: 'Generate app assignment reports, audit access, and export data for compliance reviews.',
                        slug: '/using-shiftcontrol/Reports',
                        keywords: ['reports','reporting' ],
                    },
                    items: [
                        'using-shiftcontrol/Reports/App-assignment-reports',
                    ],
                },
                {
                    type: 'category',
                    label: 'Settings',
                    link: {
                        type: 'generated-index',
                        title: 'Settings',
                        description: 'Configure your organization, manage directories, set up connectors, and control admin access.',
                        slug: '/using-shiftcontrol/Settings',
                        keywords: ['settings'],
                    },
                    items: [
                        'using-shiftcontrol/Settings/settings-overview',
                        {
                            type: 'category',
                            label: 'Personal',
                            link: {
                                type: 'generated-index',
                                title: 'Personal Settings',
                                description: 'Your account profile, theme preferences, and personal API keys.',
                                slug: '/using-shiftcontrol/Settings/personal',
                                keywords: ['personal','settings'],
                            },
                            items: [
                                'using-shiftcontrol/Settings/account-settings',
                                'using-shiftcontrol/Settings/appearance',
                                'using-shiftcontrol/Settings/user-api-keys',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Organization',
                            link: {
                                type: 'generated-index',
                                title: 'Organization Settings',
                                description: 'Organization details, departments, locations, group tags, user roles, and API keys.',
                                slug: '/using-shiftcontrol/Settings/organization',
                                keywords: ['organization','settings'],
                            },
                            items: [
                                'using-shiftcontrol/Settings/org-details',
                                'using-shiftcontrol/Settings/group-tags',
                                'using-shiftcontrol/Settings/user-roles',
                                'using-shiftcontrol/Settings/org-api-keys',
                                'using-shiftcontrol/Settings/departments',
                                'using-shiftcontrol/Settings/locations',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Connectors',
                            link: {
                                type: 'generated-index',
                                title: 'Connectors',
                                description: 'Connect identity providers (JumpCloud, Google Workspace) and HRIS systems to sync your organization data.',
                                slug: '/using-shiftcontrol/Settings/connectors',
                                keywords: ['connectors'],
                            },
                            items: [
                                'using-shiftcontrol/Integrations/Connector-management',
                                'using-shiftcontrol/Settings/directories',
                                'using-shiftcontrol/Settings/app-connectors',
                                'using-shiftcontrol/Integrations/Managing-connector-authorization',
                                {
                                    type: 'category',
                                    label: 'Connector Guides',
                                    link: {
                                        type: 'generated-index',
                                        title: 'Connector Guides',
                                        description: 'Step-by-step guides to help you set up popular connectors with ShiftControl.',
                                        slug: '/using-shiftcontrol/Integrations/connector-guides',
                                        keywords: ['connector','guides'],
                                    },
                                    items: [
                                        {
                                            type: 'category',
                                            label: 'HRIS',
                                            link: {
                                                type: 'generated-index',
                                                title: 'HRIS Connector Guides',
                                                description: 'Step-by-step guides to help you set up popular HRIS connectors with ShiftControl.',
                                                slug: '/using-shiftcontrol/Integrations/connector-guides/hris',
                                                keywords: ['connector','guides','hris'],
                                            },
                                            items: [
                                                'using-shiftcontrol/Integrations/guides/BambooHR',
                                                'using-shiftcontrol/Integrations/guides/Box',
                                                'using-shiftcontrol/Integrations/guides/Deel',
                                                'using-shiftcontrol/Integrations/guides/DreamTeam',
                                                'using-shiftcontrol/Integrations/guides/HiBob',
                                                'using-shiftcontrol/Integrations/guides/OmniHR',
                                            ],
                                        },
                                        'using-shiftcontrol/Integrations/guides/Google-Workspace',
                                        'using-shiftcontrol/Integrations/guides/JumpCloud',
                                        'using-shiftcontrol/Integrations/guides/Slack',
                                    ],
                                },
                            ],
                        },
                        {
                            type: 'category',
                            label: 'JumpCloud',
                            items: [
                                'using-shiftcontrol/Settings/jumpcloud-admins',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Google Workspace',
                            items: [
                                'using-shiftcontrol/Settings/google-admins',
                            ],
                        },
                    ],
                },
                'using-shiftcontrol/API/ShiftControl-api',
                {
                    type: 'category',
                    label: 'JumpCloud',
                    link: {
                        type: 'generated-index',
                        title: 'JumpCloud',
                        description: 'Configure JumpCloud as your identity provider, set up Google Workspace as an IdP, and manage the JumpCloud integration.',
                        slug: '/using-shiftcontrol/JumpCloud',
                        keywords: ['jumpcloud'],
                    },
                    items: [
                        'using-shiftcontrol/JumpCloud/Use-Google-Workspace-as-an-IdP',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Partnerships',
            link: {
                type: 'generated-index',
                title: 'Partnerships',
                description: 'Security partnerships and Google Workspace reseller services to complement your ShiftControl setup.',
                slug: '/using-shiftcontrol/Partnerships',
                keywords: ['jumpcloud'],
            },
            items: [
                'partnerships/Blackpanda-ir1',
                {
                    type: 'category',
                    label: 'Google Workspace Reseller',
                    items: [
                        'partnerships/Google-Workspace-Reseller/Google-Workspace-billing-transfer',
                        'partnerships/Google-Workspace-Reseller/Managing-Google-Workspace-licenses'
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Onboarding to ShiftControl',
            link: {
                type: 'generated-index',
                title: 'Onboarding to ShiftControl',
                description: 'Set up ShiftControl for your organization — what to prepare, how to onboard, and what to do after.',
                slug: '/onboarding',
                keywords: ['onboarding', 'setup'],
            },
            items: [
                'onboarding/Onboarding-intro',
                'onboarding/Before-onboarding',
                'onboarding/During-onboarding',
                'onboarding/After-onboarding',
            ],
        },
    ],
    appGuidesSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'App Guides',
            items: [
                'app-guides/Atlassian',
                'app-guides/AWS',
                'app-guides/Google-Workspace',
                'app-guides/Microsoft-Azure',
                'app-guides/Slack',
            ],
        },
    ],
    employeeGuideSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'Employee Guide',
            collapsed: false,
            items: [
                'employee-guide/what-is-shiftcontrol',
                {
                    type: 'category',
                    label: 'Employee Portal',
                    link: {
                        type: 'generated-index',
                        title: 'Employee Portal',
                        description: 'Your app dashboard, org chart, and account security — everything you see as an employee.',
                        slug: '/employee-guide/employee-portal',
                        keywords: ['employee', 'portal', 'apps'],
                    },
                    items: [
                        'employee-guide/employee-portal/your-apps',
                        'employee-guide/employee-portal/org-chart',
                        'employee-guide/employee-portal/account-security',
                    ],
                },
                'employee-guide/onboarding',
            ],
        },
    ],
};

export default sidebars;
