import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// @ts-ignore
import type { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const standardLinks: SidebarConfig = [
    {
        type: 'link',
        label: 'ShiftControl website',
        href: 'https://shiftcontrol.io',
    },
    {
        type: 'link',
        label: 'Release Notes',
        href: 'https://journey.shiftcontrol.io',
    },
];

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    mainSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'Get Started',
            items: [
                'introduction',
                'getting-started/quickstart',
            ],
        },
        {
            type: 'category',
            collapsed: false,
            label: 'Using ShiftControl',
            items: [
                'using-shiftcontrol/shiftcontrol-dashboard',
                'using-shiftcontrol/using-the-command-bar',
                'using-shiftcontrol/task-management',
                {
                    type: 'category',
                    label: 'Users',
                    items: [
                        'using-shiftcontrol/Users/User-management',
                        'using-shiftcontrol/Users/Adding-a-user',
                        'using-shiftcontrol/Users/Editing-a-user',
                    ],
                },
                {
                    type: 'category',
                    label: 'Groups',
                    items: [
                        'using-shiftcontrol/Groups/Group-management',
                        'using-shiftcontrol/Groups/Adding-a-group',
                        'using-shiftcontrol/Groups/Editing-a-group',
                        'using-shiftcontrol/Groups/Syncing-groups-with-google',
                    ],
                },
                {
                    type: 'category',
                    label: 'Apps',
                    items: [
                        'using-shiftcontrol/Apps/App-management',
                        'using-shiftcontrol/Apps/Adding-an-app',
                        'using-shiftcontrol/Apps/Editing-an-app',
                        'using-shiftcontrol/Apps/App-discovery',
                    ],
                },
                {
                    type: 'category',
                    label: 'Integrations',
                    items: [
                        'using-shiftcontrol/Integrations/Integration-management',
                        'using-shiftcontrol/Integrations/Managing-integration-authorization',
                    ],
                },
                {
                    type: 'category',
                    label: 'Reports',
                    items: [
                        'using-shiftcontrol/Reports/App-assignment-reports',
                    ],
                },
                {
                    type: 'category',
                    label: 'API',
                    items: [
                        'using-shiftcontrol/API/ShiftControl-api',
                        'using-shiftcontrol/API/API-key-management',
                        'using-shiftcontrol/API/Adding-an-api-key',
                        'using-shiftcontrol/API/Editing-an-api-key',
                    ],
                },
            ],
        },
    ],
    onboardingSidebar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'Onboarding',
            items: [
                'onboarding/Onboarding-intro',
                'onboarding/Before-onboarding',
                'onboarding/During-onboarding',
                'onboarding/After-onboarding',
            ],
        },
    ],
    appGuidesSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'App Guides',
            items: [
                'app-guides/Atlassian',
                'app-guides/AWS',
                'app-guides/Google-Workspace',
                'app-guides/Microsoft-Azure',
                'app-guides/Slack',
            ],
        },
    ],
};

export default sidebars;
