import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// @ts-ignore
import type { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const standardLinks: SidebarConfig = [
    {
        type: 'link',
        label: 'ShiftControl website',
        href: 'https://shiftcontrol.io',
    },
    {
        type: 'link',
        label: 'Release Notes',
        href: 'https://journey.shiftcontrol.io',
    },
    {
        type: 'link',
        label: 'Log in to ShiftControl',
        href: 'https://app.shiftcontrol.io',

    },
    {
        type: 'link',
        label: 'Support',
        href: 'mailto:support@shiftcontrol.io',
    },
];

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    mainSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'Get Started',
            items: [
                'introduction',
                'getting-started/quickstart',
            ],
        },
        {
            type: 'category',
            collapsed: false,
            label: 'Using ShiftControl',
            items: [
                {
                    type: 'category',
                    label: 'Dashboards',
                    link: {
                        type: 'generated-index',
                        title: 'Dashboards',
                        description: 'Overview of ShiftControl Dashboards and their features.',
                        slug: '/using-shiftcontrol/Dashboards',
                        keywords: ['dashboards'],
                    },
                    items: [
                        'using-shiftcontrol/Dashboards/app-permissions',
                        'using-shiftcontrol/Dashboards/app-spend',
                    ],
                },
                'using-shiftcontrol/using-the-command-bar',
                'using-shiftcontrol/task-management',
                {
                    type: 'category',
                    label: 'Users',
                    link: {
                        type: 'generated-index',
                        title: 'Users',
                        description: 'Overview of User Management in ShiftControl.',
                        slug: '/using-shiftcontrol/Users',
                        keywords: ['users','user-management'],
                    },
                    items: [
                        'using-shiftcontrol/Users/User-management',
                        'using-shiftcontrol/Users/Adding-a-user',
                        'using-shiftcontrol/Users/Editing-a-user',
                    ],
                },
                {
                    type: 'category',
                    label: 'Groups',
                    link: {
                        type: 'generated-index',
                        title: 'Groups',
                        description: 'Overview of Group Management in ShiftControl.',
                        slug: '/using-shiftcontrol/Groups',
                        keywords: ['groups','group-management'],
                    },
                    items: [
                        'using-shiftcontrol/Groups/Group-management',
                        'using-shiftcontrol/Groups/Adding-a-group',
                        'using-shiftcontrol/Groups/Editing-a-group',
                        'using-shiftcontrol/Groups/Syncing-groups-with-google',
                    ],
                },
                {
                    type: 'category',
                    label: 'Apps',
                    link: {
                        type: 'generated-index',
                        title: 'Apps',
                        description: 'Overview of App Management in ShiftControl.',
                        slug: '/using-shiftcontrol/Apps',
                        keywords: ['apps','app-management'],
                    },
                    items: [
                        'using-shiftcontrol/Apps/App-management',
                        'using-shiftcontrol/Apps/Adding-an-app',
                        'using-shiftcontrol/Apps/Editing-an-app',
                        'using-shiftcontrol/Apps/App-discovery',
                    ],
                },
                {
                    type: 'category',
                    label: 'Integrations',
                    link: {
                        type: 'generated-index',
                        title: 'Integrations',
                        description: 'Overview of Integration Management in ShiftControl.',
                        slug: '/using-shiftcontrol/Integrations',
                        keywords: ['integrations','integration-management'],
                    },
                    items: [
                        'using-shiftcontrol/Integrations/Integration-management',
                        'using-shiftcontrol/Integrations/Managing-integration-authorization',
                        {
                            type: 'category',
                            label: 'Integration Guides',
                            link: {
                                type: 'generated-index',
                                title: 'Integration Guides',
                                description: 'Step-by-step guides to help you set up popular integrations with ShiftControl.',
                                slug: '/using-shiftcontrol/Integrations/integration-guides',
                                keywords: ['integration','guides'],
                            },
                            items: [
                                {
                                    type: 'category',
                                    label: 'HRIS',
                                    link: {
                                        type: 'generated-index',
                                        title: 'HRIS Integration Guides',
                                        description: 'Step-by-step guides to help you set up popular HRIS integrations with ShiftControl.',
                                        slug: '/using-shiftcontrol/Integrations/integration-guides/hris',
                                        keywords: ['integration','guides','hris'],
                                    },
                                    items: [
                                        'using-shiftcontrol/Integrations/guides/BambooHR',
                                        'using-shiftcontrol/Integrations/guides/Box',
                                        'using-shiftcontrol/Integrations/guides/Deel',
                                        'using-shiftcontrol/Integrations/guides/DreamTeam',
                                        'using-shiftcontrol/Integrations/guides/HiBob',
                                        'using-shiftcontrol/Integrations/guides/OmniHR',
                                    ],
                                },
                                'using-shiftcontrol/Integrations/guides/Google-Workspace',
                                'using-shiftcontrol/Integrations/guides/JumpCloud',
                                'using-shiftcontrol/Integrations/guides/Slack',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Reports',
                    link: {
                        type: 'generated-index',
                        title: 'Reports',
                        description: 'Overview of Reporting in ShiftControl.',
                        slug: '/using-shiftcontrol/Reports',
                        keywords: ['reports','reporting' ],
                    },
                    items: [
                        'using-shiftcontrol/Reports/App-assignment-reports',
                    ],
                },
                {
                    type: 'category',
                    label: 'Settings',
                    link: {
                        type: 'generated-index',
                        title: 'Settings',
                        description: 'Overview of Settings in ShiftControl.',
                        slug: '/using-shiftcontrol/Settings',
                        keywords: ['settings'],
                    },
                    items: [
                        'using-shiftcontrol/Settings/settings-overview',
                        {
                            type: 'category',
                            label: 'Personal',
                            link: {
                                type: 'generated-index',
                                title: 'Personal Settings',
                                description: 'Overview of Personal Settings in ShiftControl.',
                                slug: '/using-shiftcontrol/Settings/personal',
                                keywords: ['personal','settings'],
                            },
                            items: [
                                'using-shiftcontrol/Settings/account-settings',
                                'using-shiftcontrol/Settings/appearance',
                                'using-shiftcontrol/Settings/user-api-keys',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Organization',
                            link: {
                                type: 'generated-index',
                                title: 'Organization Settings',
                                description: 'Overview of Organization Settings in ShiftControl.',
                                slug: '/using-shiftcontrol/Settings/organization',
                                keywords: ['organization','settings'],
                            },
                            items: [
                                'using-shiftcontrol/Settings/org-details',
                                'using-shiftcontrol/Settings/group-tags',
                                'using-shiftcontrol/Settings/user-roles',
                                'using-shiftcontrol/Settings/org-api-keys',
                                'using-shiftcontrol/Settings/departments',
                                'using-shiftcontrol/Settings/locations',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'Connectors',
                            link: {
                                type: 'generated-index',
                                title: 'Connectors',
                                description: 'Overview of Connectors in ShiftControl.',
                                slug: '/using-shiftcontrol/Settings/connectors',
                                keywords: ['connectors'],
                            },
                            items: [
                                'using-shiftcontrol/Settings/directories',
                                'using-shiftcontrol/Settings/app-connectors',
                            ],
                        },
                        {
                            type: 'category',
                            label: 'JumpCloud',
                            items: [
                                'using-shiftcontrol/Settings/jumpcloud-admins',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'API',
                    link: {
                        type: 'generated-index',
                        title: 'API',
                        description: 'Overview of the ShiftControl API.',
                        slug: '/using-shiftcontrol/API',
                        keywords: ['api'],
                    },
                    items: [
                        'using-shiftcontrol/API/ShiftControl-api',
                        'using-shiftcontrol/API/API-key-management',
                        'using-shiftcontrol/API/Adding-an-api-key',
                        'using-shiftcontrol/API/Editing-an-api-key',
                    ],
                },
                {
                    type: 'category',
                    label: 'JumpCloud',
                    link: {
                        type: 'generated-index',
                        title: 'JumpCloud',
                        description: 'Overview of using ShiftControl with JumpCloud.',
                        slug: '/using-shiftcontrol/JumpCloud',
                        keywords: ['jumpcloud'],
                    },
                    items: [
                        'using-shiftcontrol/JumpCloud/Use-Google-Workspace-as-an-IdP',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Partnerships',
            link: {
                type: 'generated-index',
                title: 'Partnerships',
                description: 'Overview of ShiftControl Partnerships.',
                slug: '/using-shiftcontrol/Partnerships',
                keywords: ['jumpcloud'],
            },
            items: [
                'partnerships/Blackpanda-ir1',
                {
                    type: 'category',
                    label: 'Google Workspace Reseller',
                    items: [
                        'partnerships/Google-Workspace-Reseller/Google-Workspace-billing-transfer',
                        'partnerships/Google-Workspace-Reseller/Managing-Google-Workspace-licenses'
                    ],
                },
            ],
        },
    ],
    onboardingSidebar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'Onboarding',
            items: [
                'onboarding/Onboarding-intro',
                'onboarding/Before-onboarding',
                'onboarding/During-onboarding',
                'onboarding/After-onboarding',
            ],
        },
    ],
    appGuidesSideBar: [
        ...standardLinks,
        {
            type: 'category',
            label: 'App Guides',
            items: [
                'app-guides/Atlassian',
                'app-guides/AWS',
                'app-guides/Google-Workspace',
                'app-guides/Microsoft-Azure',
                'app-guides/Slack',
            ],
        },
    ],
};

export default sidebars;
